name: Python application

on:
  push:
    branches: 
      - "main"
      - "dev"  # Voeg hier de dev branch toe
  pull_request:
    branches: 
      - "main"
      - "dev"  # Voeg hier de dev branch toe
  schedule:
    - cron: '0 6 * * 1'  # Dit zorgt voor een wekelijkse scan op maandag om 06:00

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest bandit pip-audit detect-secrets
        
    - name: Lint with flake8
      run: |
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: pytest
    - name: Security scan with Bandit
      run: bandit -r . || exit 1
    - name: Dependency audit with pip-audit
      run: pip-audit || exit 1
    - name: Scan for secrets
      run: detect-secrets scan || exit 1
